apiVersion: v1
kind: Config
clusters:
- name: my-cluster
  cluster:
    server: https://my-cluster-endpoint
    certificate-authority-data: <base64-encoded-ca-cert>
users:
- name: my-user
  user:
    client-certificate-data: <base64-encoded-client-cert>
    client-key-data: <base64-encoded-client-key>
contexts:
- name: my-context
  context:
    cluster: my-cluster
    user: my-user
current-context: my-context
